app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO
    com.story_magic.api: INFO
    org.springframework.web: WARN
