spring:
  application:
    name: story-magic-api
  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: ${PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
